# Generated by Django 3.1.4 on 2020-12-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_product_product_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_quantity',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
