# Generated by Django 3.1.4 on 2021-01-01 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_order_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
