# Generated by Django 3.1.4 on 2021-01-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_product_added_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='added_data',
            new_name='added_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_old_prize',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_prize',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productimage_10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productimage_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productimage_7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productimage_8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productimage_9',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_customization',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_min_quantity',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
