# Generated by Django 3.1.4 on 2021-01-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_gifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalized',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Personalized/')),
                ('subcategory_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tresures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Tresures/')),
                ('subcategory_name', models.CharField(max_length=100)),
            ],
        ),
    ]
